### ISSUE TITLE
[CRITICAL] 未处理插件卸载事件

### ISSUE THREAD

**Issue by alex3236** [moran0710/MinecraftServer_BaiduNetdisk_backup#1]
![5370dcfb01a1146e407c284a3607558b](https://github.com/moran0710/MinecraftServer_BaiduNetdisk_backup/assets/45303195/fef7c63b-1424-4d49-94c0-4fac3b79b1ac)
插件加载时会创建scheduler，卸载时没有处理，导致插件重载后遗留scheduler

**Comment by moran0710** [comment]
感谢（
现在在学校，修复可能会在明后天提交

**Comment by moran0710** [comment]
在#32ca6f9修复
