### ISSUE TITLE
不支持python3.9

### ISSUE THREAD

**Issue by 3356153957** [moran0710/MinecraftServer_BaiduNetdisk_backup#3]
[MCDR] [04:39:47] [TaskExecutor/ERROR]: 插件 baidu_netdisk_backup@1.0.0 加载失败
[MCDR] [04:39:47] [TaskExecutor/ERROR]: 插件 baidu_netdisk_backup@1.0.0 的 Python 依赖库需求未被满足: version unsatisfied for required package 'parse': expect '==1.20.1', but installed <Version('1.20.2')>

**Comment by moran0710** [comment]
我写代码的时候就是3.9.......
按照报错的话，你需要重新安装依赖来满足依赖版本

`pip uninstall parse -y`
`pip install parse==1.20.1`

这样补充依赖试试

**Comment by moran0710** [comment]
那么我先close了
